// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: conveyor/v1/queue.proto

package conveyorv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LeaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queue         string                 `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"`
	WorkerId      string                 `protobuf:"bytes,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	MaxInFlight   int32                  `protobuf:"varint,3,opt,name=max_in_flight,json=maxInFlight,proto3" json:"max_in_flight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaseRequest) Reset() {
	*x = LeaseRequest{}
	mi := &file_conveyor_v1_queue_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseRequest) ProtoMessage() {}

func (x *LeaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_conveyor_v1_queue_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseRequest.ProtoReflect.Descriptor instead.
func (*LeaseRequest) Descriptor() ([]byte, []int) {
	return file_conveyor_v1_queue_proto_rawDescGZIP(), []int{0}
}

func (x *LeaseRequest) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *LeaseRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *LeaseRequest) GetMaxInFlight() int32 {
	if x != nil {
		return x.MaxInFlight
	}
	return 0
}

type LeaseResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	JobId                string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Epoch                int64                  `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	IdempotencyKey       string                 `protobuf:"bytes,3,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	Handler              string                 `protobuf:"bytes,4,opt,name=handler,proto3" json:"handler,omitempty"`
	Payload              []byte                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	Attempt              int32                  `protobuf:"varint,6,opt,name=attempt,proto3" json:"attempt,omitempty"`
	LeaseExpiresAtUnixMs int64                  `protobuf:"varint,7,opt,name=lease_expires_at_unix_ms,json=leaseExpiresAtUnixMs,proto3" json:"lease_expires_at_unix_ms,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *LeaseResponse) Reset() {
	*x = LeaseResponse{}
	mi := &file_conveyor_v1_queue_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseResponse) ProtoMessage() {}

func (x *LeaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_conveyor_v1_queue_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseResponse.ProtoReflect.Descriptor instead.
func (*LeaseResponse) Descriptor() ([]byte, []int) {
	return file_conveyor_v1_queue_proto_rawDescGZIP(), []int{1}
}

func (x *LeaseResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *LeaseResponse) GetEpoch() int64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *LeaseResponse) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *LeaseResponse) GetHandler() string {
	if x != nil {
		return x.Handler
	}
	return ""
}

func (x *LeaseResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *LeaseResponse) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *LeaseResponse) GetLeaseExpiresAtUnixMs() int64 {
	if x != nil {
		return x.LeaseExpiresAtUnixMs
	}
	return 0
}

type AckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Epoch         int64                  `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	WorkerId      string                 `protobuf:"bytes,3,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckRequest) Reset() {
	*x = AckRequest{}
	mi := &file_conveyor_v1_queue_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckRequest) ProtoMessage() {}

func (x *AckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_conveyor_v1_queue_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckRequest.ProtoReflect.Descriptor instead.
func (*AckRequest) Descriptor() ([]byte, []int) {
	return file_conveyor_v1_queue_proto_rawDescGZIP(), []int{2}
}

func (x *AckRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *AckRequest) GetEpoch() int64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *AckRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

type AckResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// accepted is false when epoch is stale, meaning the job was already reclaimed
	// and reassigned; the caller's work was not credited and should be discarded.
	Accepted      bool `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckResponse) Reset() {
	*x = AckResponse{}
	mi := &file_conveyor_v1_queue_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckResponse) ProtoMessage() {}

func (x *AckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_conveyor_v1_queue_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckResponse.ProtoReflect.Descriptor instead.
func (*AckResponse) Descriptor() ([]byte, []int) {
	return file_conveyor_v1_queue_proto_rawDescGZIP(), []int{3}
}

func (x *AckResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

type NackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Epoch         int64                  `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	WorkerId      string                 `protobuf:"bytes,3,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NackRequest) Reset() {
	*x = NackRequest{}
	mi := &file_conveyor_v1_queue_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NackRequest) ProtoMessage() {}

func (x *NackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_conveyor_v1_queue_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NackRequest.ProtoReflect.Descriptor instead.
func (*NackRequest) Descriptor() ([]byte, []int) {
	return file_conveyor_v1_queue_proto_rawDescGZIP(), []int{4}
}

func (x *NackRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *NackRequest) GetEpoch() int64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *NackRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *NackRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type NackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	DeadLettered  bool                   `protobuf:"varint,2,opt,name=dead_lettered,json=deadLettered,proto3" json:"dead_lettered,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NackResponse) Reset() {
	*x = NackResponse{}
	mi := &file_conveyor_v1_queue_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NackResponse) ProtoMessage() {}

func (x *NackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_conveyor_v1_queue_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NackResponse.ProtoReflect.Descriptor instead.
func (*NackResponse) Descriptor() ([]byte, []int) {
	return file_conveyor_v1_queue_proto_rawDescGZIP(), []int{5}
}

func (x *NackResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *NackResponse) GetDeadLettered() bool {
	if x != nil {
		return x.DeadLettered
	}
	return false
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Epoch         int64                  `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	WorkerId      string                 `protobuf:"bytes,3,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_conveyor_v1_queue_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_conveyor_v1_queue_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_conveyor_v1_queue_proto_rawDescGZIP(), []int{6}
}

func (x *HeartbeatRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *HeartbeatRequest) GetEpoch() int64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *HeartbeatRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

type HeartbeatResponse struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Accepted                bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	NewLeaseExpiresAtUnixMs int64                  `protobuf:"varint,2,opt,name=new_lease_expires_at_unix_ms,json=newLeaseExpiresAtUnixMs,proto3" json:"new_lease_expires_at_unix_ms,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_conveyor_v1_queue_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_conveyor_v1_queue_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_conveyor_v1_queue_proto_rawDescGZIP(), []int{7}
}

func (x *HeartbeatResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *HeartbeatResponse) GetNewLeaseExpiresAtUnixMs() int64 {
	if x != nil {
		return x.NewLeaseExpiresAtUnixMs
	}
	return 0
}

var File_conveyor_v1_queue_proto protoreflect.FileDescriptor

const file_conveyor_v1_queue_proto_rawDesc = "" +
	"\n" +
	"\x17conveyor/v1/queue.proto\x12\vconveyor.v1\"e\n" +
	"\fLeaseRequest\x12\x14\n" +
	"\x05queue\x18\x01 \x01(\tR\x05queue\x12\x1b\n" +
	"\tworker_id\x18\x02 \x01(\tR\bworkerId\x12\"\n" +
	"\rmax_in_flight\x18\x03 \x01(\x05R\vmaxInFlight\"\xeb\x01\n" +
	"\rLeaseResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x14\n" +
	"\x05epoch\x18\x02 \x01(\x03R\x05epoch\x12'\n" +
	"\x0fidempotency_key\x18\x03 \x01(\tR\x0eidempotencyKey\x12\x18\n" +
	"\ahandler\x18\x04 \x01(\tR\ahandler\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\x12\x18\n" +
	"\aattempt\x18\x06 \x01(\x05R\aattempt\x126\n" +
	"\x18lease_expires_at_unix_ms\x18\a \x01(\x03R\x14leaseExpiresAtUnixMs\"V\n" +
	"\n" +
	"AckRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x14\n" +
	"\x05epoch\x18\x02 \x01(\x03R\x05epoch\x12\x1b\n" +
	"\tworker_id\x18\x03 \x01(\tR\bworkerId\")\n" +
	"\vAckResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\"o\n" +
	"\vNackRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x14\n" +
	"\x05epoch\x18\x02 \x01(\x03R\x05epoch\x12\x1b\n" +
	"\tworker_id\x18\x03 \x01(\tR\bworkerId\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"O\n" +
	"\fNackResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12#\n" +
	"\rdead_lettered\x18\x02 \x01(\bR\fdeadLettered\"\\\n" +
	"\x10HeartbeatRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x14\n" +
	"\x05epoch\x18\x02 \x01(\x03R\x05epoch\x12\x1b\n" +
	"\tworker_id\x18\x03 \x01(\tR\bworkerId\"n\n" +
	"\x11HeartbeatResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12=\n" +
	"\x1cnew_lease_expires_at_unix_ms\x18\x02 \x01(\x03R\x17newLeaseExpiresAtUnixMs2\x8d\x02\n" +
	"\x06Broker\x12@\n" +
	"\x05Lease\x12\x19.conveyor.v1.LeaseRequest\x1a\x1a.conveyor.v1.LeaseResponse0\x01\x128\n" +
	"\x03Ack\x12\x17.conveyor.v1.AckRequest\x1a\x18.conveyor.v1.AckResponse\x12;\n" +
	"\x04Nack\x12\x18.conveyor.v1.NackRequest\x1a\x19.conveyor.v1.NackResponse\x12J\n" +
	"\tHeartbeat\x12\x1d.conveyor.v1.HeartbeatRequest\x1a\x1e.conveyor.v1.HeartbeatResponseB3Z1conveyor/internal/genproto/conveyor/v1;conveyorv1b\x06proto3"

var (
	file_conveyor_v1_queue_proto_rawDescOnce sync.Once
	file_conveyor_v1_queue_proto_rawDescData []byte
)

func file_conveyor_v1_queue_proto_rawDescGZIP() []byte {
	file_conveyor_v1_queue_proto_rawDescOnce.Do(func() {
		file_conveyor_v1_queue_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_conveyor_v1_queue_proto_rawDesc), len(file_conveyor_v1_queue_proto_rawDesc)))
	})
	return file_conveyor_v1_queue_proto_rawDescData
}

var file_conveyor_v1_queue_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_conveyor_v1_queue_proto_goTypes = []any{
	(*LeaseRequest)(nil),      // 0: conveyor.v1.LeaseRequest
	(*LeaseResponse)(nil),     // 1: conveyor.v1.LeaseResponse
	(*AckRequest)(nil),        // 2: conveyor.v1.AckRequest
	(*AckResponse)(nil),       // 3: conveyor.v1.AckResponse
	(*NackRequest)(nil),       // 4: conveyor.v1.NackRequest
	(*NackResponse)(nil),      // 5: conveyor.v1.NackResponse
	(*HeartbeatRequest)(nil),  // 6: conveyor.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil), // 7: conveyor.v1.HeartbeatResponse
}
var file_conveyor_v1_queue_proto_depIdxs = []int32{
	0, // 0: conveyor.v1.Broker.Lease:input_type -> conveyor.v1.LeaseRequest
	2, // 1: conveyor.v1.Broker.Ack:input_type -> conveyor.v1.AckRequest
	4, // 2: conveyor.v1.Broker.Nack:input_type -> conveyor.v1.NackRequest
	6, // 3: conveyor.v1.Broker.Heartbeat:input_type -> conveyor.v1.HeartbeatRequest
	1, // 4: conveyor.v1.Broker.Lease:output_type -> conveyor.v1.LeaseResponse
	3, // 5: conveyor.v1.Broker.Ack:output_type -> conveyor.v1.AckResponse
	5, // 6: conveyor.v1.Broker.Nack:output_type -> conveyor.v1.NackResponse
	7, // 7: conveyor.v1.Broker.Heartbeat:output_type -> conveyor.v1.HeartbeatResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_conveyor_v1_queue_proto_init() }
func file_conveyor_v1_queue_proto_init() {
	if File_conveyor_v1_queue_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_conveyor_v1_queue_proto_rawDesc), len(file_conveyor_v1_queue_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_conveyor_v1_queue_proto_goTypes,
		DependencyIndexes: file_conveyor_v1_queue_proto_depIdxs,
		MessageInfos:      file_conveyor_v1_queue_proto_msgTypes,
	}.Build()
	File_conveyor_v1_queue_proto = out.File
	file_conveyor_v1_queue_proto_goTypes = nil
	file_conveyor_v1_queue_proto_depIdxs = nil
}
