// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: conveyor/v1/queue.proto

package conveyorv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	v1 "conveyor/internal/genproto/conveyor/v1"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// BrokerServiceName is the fully-qualified name of the BrokerService service.
	BrokerServiceName = "conveyor.v1.BrokerService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// BrokerServiceSubmitProcedure is the fully-qualified name of the BrokerService's Submit RPC.
	BrokerServiceSubmitProcedure = "/conveyor.v1.BrokerService/Submit"
	// BrokerServiceGetProcedure is the fully-qualified name of the BrokerService's Get RPC.
	BrokerServiceGetProcedure = "/conveyor.v1.BrokerService/Get"
	// BrokerServiceStatsProcedure is the fully-qualified name of the BrokerService's Stats RPC.
	BrokerServiceStatsProcedure = "/conveyor.v1.BrokerService/Stats"
	// BrokerServiceListJobsProcedure is the fully-qualified name of the BrokerService's ListJobs RPC.
	BrokerServiceListJobsProcedure = "/conveyor.v1.BrokerService/ListJobs"
	// BrokerServiceReplayJobProcedure is the fully-qualified name of the BrokerService's ReplayJob RPC.
	BrokerServiceReplayJobProcedure = "/conveyor.v1.BrokerService/ReplayJob"
	// BrokerServiceLeaseProcedure is the fully-qualified name of the BrokerService's Lease RPC.
	BrokerServiceLeaseProcedure = "/conveyor.v1.BrokerService/Lease"
	// BrokerServiceAckProcedure is the fully-qualified name of the BrokerService's Ack RPC.
	BrokerServiceAckProcedure = "/conveyor.v1.BrokerService/Ack"
	// BrokerServiceNackProcedure is the fully-qualified name of the BrokerService's Nack RPC.
	BrokerServiceNackProcedure = "/conveyor.v1.BrokerService/Nack"
	// BrokerServiceHeartbeatProcedure is the fully-qualified name of the BrokerService's Heartbeat RPC.
	BrokerServiceHeartbeatProcedure = "/conveyor.v1.BrokerService/Heartbeat"
)

// BrokerServiceClient is a client for the conveyor.v1.BrokerService service.
type BrokerServiceClient interface {
	// Submit enqueues a job. If idempotency_key is set and a job with that key
	// already exists on the queue, the existing job is returned and no new job is
	// created.
	Submit(context.Context, *connect.Request[v1.SubmitRequest]) (*connect.Response[v1.SubmitResponse], error)
	// Get looks up a single job by ID.
	Get(context.Context, *connect.Request[v1.GetRequest]) (*connect.Response[v1.GetResponse], error)
	// Stats reports per-queue job counts by state.
	Stats(context.Context, *connect.Request[v1.StatsRequest]) (*connect.Response[v1.StatsResponse], error)
	// ListJobs returns jobs filtered by queue and state -- the dead-letter queue
	// is just a state filter over this.
	ListJobs(context.Context, *connect.Request[v1.ListJobsRequest]) (*connect.Response[v1.ListJobsResponse], error)
	// ReplayJob returns a dead-lettered job to its queue with a fresh retry
	// budget.
	ReplayJob(context.Context, *connect.Request[v1.ReplayJobRequest]) (*connect.Response[v1.ReplayJobResponse], error)
	// Lease streams job assignments to a worker as they become available for the
	// requested queue, up to max_in_flight concurrently-leased jobs at a time.
	Lease(context.Context, *connect.Request[v1.LeaseRequest]) (*connect.ServerStreamForClient[v1.LeaseResponse], error)
	// Ack marks a leased job as successfully completed.
	Ack(context.Context, *connect.Request[v1.AckRequest]) (*connect.Response[v1.AckResponse], error)
	// Nack marks a leased job as failed. The broker schedules it for retry with
	// exponential backoff and jitter, or dead-letters it once max_retries is
	// exhausted.
	Nack(context.Context, *connect.Request[v1.NackRequest]) (*connect.Response[v1.NackResponse], error)
	// Heartbeat renews a job's lease so a long-running handler isn't reclaimed as
	// if it had crashed.
	Heartbeat(context.Context, *connect.Request[v1.HeartbeatRequest]) (*connect.Response[v1.HeartbeatResponse], error)
}

// NewBrokerServiceClient constructs a client for the conveyor.v1.BrokerService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewBrokerServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) BrokerServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	brokerServiceMethods := v1.File_conveyor_v1_queue_proto.Services().ByName("BrokerService").Methods()
	return &brokerServiceClient{
		submit: connect.NewClient[v1.SubmitRequest, v1.SubmitResponse](
			httpClient,
			baseURL+BrokerServiceSubmitProcedure,
			connect.WithSchema(brokerServiceMethods.ByName("Submit")),
			connect.WithClientOptions(opts...),
		),
		get: connect.NewClient[v1.GetRequest, v1.GetResponse](
			httpClient,
			baseURL+BrokerServiceGetProcedure,
			connect.WithSchema(brokerServiceMethods.ByName("Get")),
			connect.WithClientOptions(opts...),
		),
		stats: connect.NewClient[v1.StatsRequest, v1.StatsResponse](
			httpClient,
			baseURL+BrokerServiceStatsProcedure,
			connect.WithSchema(brokerServiceMethods.ByName("Stats")),
			connect.WithClientOptions(opts...),
		),
		listJobs: connect.NewClient[v1.ListJobsRequest, v1.ListJobsResponse](
			httpClient,
			baseURL+BrokerServiceListJobsProcedure,
			connect.WithSchema(brokerServiceMethods.ByName("ListJobs")),
			connect.WithClientOptions(opts...),
		),
		replayJob: connect.NewClient[v1.ReplayJobRequest, v1.ReplayJobResponse](
			httpClient,
			baseURL+BrokerServiceReplayJobProcedure,
			connect.WithSchema(brokerServiceMethods.ByName("ReplayJob")),
			connect.WithClientOptions(opts...),
		),
		lease: connect.NewClient[v1.LeaseRequest, v1.LeaseResponse](
			httpClient,
			baseURL+BrokerServiceLeaseProcedure,
			connect.WithSchema(brokerServiceMethods.ByName("Lease")),
			connect.WithClientOptions(opts...),
		),
		ack: connect.NewClient[v1.AckRequest, v1.AckResponse](
			httpClient,
			baseURL+BrokerServiceAckProcedure,
			connect.WithSchema(brokerServiceMethods.ByName("Ack")),
			connect.WithClientOptions(opts...),
		),
		nack: connect.NewClient[v1.NackRequest, v1.NackResponse](
			httpClient,
			baseURL+BrokerServiceNackProcedure,
			connect.WithSchema(brokerServiceMethods.ByName("Nack")),
			connect.WithClientOptions(opts...),
		),
		heartbeat: connect.NewClient[v1.HeartbeatRequest, v1.HeartbeatResponse](
			httpClient,
			baseURL+BrokerServiceHeartbeatProcedure,
			connect.WithSchema(brokerServiceMethods.ByName("Heartbeat")),
			connect.WithClientOptions(opts...),
		),
	}
}

// brokerServiceClient implements BrokerServiceClient.
type brokerServiceClient struct {
	submit    *connect.Client[v1.SubmitRequest, v1.SubmitResponse]
	get       *connect.Client[v1.GetRequest, v1.GetResponse]
	stats     *connect.Client[v1.StatsRequest, v1.StatsResponse]
	listJobs  *connect.Client[v1.ListJobsRequest, v1.ListJobsResponse]
	replayJob *connect.Client[v1.ReplayJobRequest, v1.ReplayJobResponse]
	lease     *connect.Client[v1.LeaseRequest, v1.LeaseResponse]
	ack       *connect.Client[v1.AckRequest, v1.AckResponse]
	nack      *connect.Client[v1.NackRequest, v1.NackResponse]
	heartbeat *connect.Client[v1.HeartbeatRequest, v1.HeartbeatResponse]
}

// Submit calls conveyor.v1.BrokerService.Submit.
func (c *brokerServiceClient) Submit(ctx context.Context, req *connect.Request[v1.SubmitRequest]) (*connect.Response[v1.SubmitResponse], error) {
	return c.submit.CallUnary(ctx, req)
}

// Get calls conveyor.v1.BrokerService.Get.
func (c *brokerServiceClient) Get(ctx context.Context, req *connect.Request[v1.GetRequest]) (*connect.Response[v1.GetResponse], error) {
	return c.get.CallUnary(ctx, req)
}

// Stats calls conveyor.v1.BrokerService.Stats.
func (c *brokerServiceClient) Stats(ctx context.Context, req *connect.Request[v1.StatsRequest]) (*connect.Response[v1.StatsResponse], error) {
	return c.stats.CallUnary(ctx, req)
}

// ListJobs calls conveyor.v1.BrokerService.ListJobs.
func (c *brokerServiceClient) ListJobs(ctx context.Context, req *connect.Request[v1.ListJobsRequest]) (*connect.Response[v1.ListJobsResponse], error) {
	return c.listJobs.CallUnary(ctx, req)
}

// ReplayJob calls conveyor.v1.BrokerService.ReplayJob.
func (c *brokerServiceClient) ReplayJob(ctx context.Context, req *connect.Request[v1.ReplayJobRequest]) (*connect.Response[v1.ReplayJobResponse], error) {
	return c.replayJob.CallUnary(ctx, req)
}

// Lease calls conveyor.v1.BrokerService.Lease.
func (c *brokerServiceClient) Lease(ctx context.Context, req *connect.Request[v1.LeaseRequest]) (*connect.ServerStreamForClient[v1.LeaseResponse], error) {
	return c.lease.CallServerStream(ctx, req)
}

// Ack calls conveyor.v1.BrokerService.Ack.
func (c *brokerServiceClient) Ack(ctx context.Context, req *connect.Request[v1.AckRequest]) (*connect.Response[v1.AckResponse], error) {
	return c.ack.CallUnary(ctx, req)
}

// Nack calls conveyor.v1.BrokerService.Nack.
func (c *brokerServiceClient) Nack(ctx context.Context, req *connect.Request[v1.NackRequest]) (*connect.Response[v1.NackResponse], error) {
	return c.nack.CallUnary(ctx, req)
}

// Heartbeat calls conveyor.v1.BrokerService.Heartbeat.
func (c *brokerServiceClient) Heartbeat(ctx context.Context, req *connect.Request[v1.HeartbeatRequest]) (*connect.Response[v1.HeartbeatResponse], error) {
	return c.heartbeat.CallUnary(ctx, req)
}

// BrokerServiceHandler is an implementation of the conveyor.v1.BrokerService service.
type BrokerServiceHandler interface {
	// Submit enqueues a job. If idempotency_key is set and a job with that key
	// already exists on the queue, the existing job is returned and no new job is
	// created.
	Submit(context.Context, *connect.Request[v1.SubmitRequest]) (*connect.Response[v1.SubmitResponse], error)
	// Get looks up a single job by ID.
	Get(context.Context, *connect.Request[v1.GetRequest]) (*connect.Response[v1.GetResponse], error)
	// Stats reports per-queue job counts by state.
	Stats(context.Context, *connect.Request[v1.StatsRequest]) (*connect.Response[v1.StatsResponse], error)
	// ListJobs returns jobs filtered by queue and state -- the dead-letter queue
	// is just a state filter over this.
	ListJobs(context.Context, *connect.Request[v1.ListJobsRequest]) (*connect.Response[v1.ListJobsResponse], error)
	// ReplayJob returns a dead-lettered job to its queue with a fresh retry
	// budget.
	ReplayJob(context.Context, *connect.Request[v1.ReplayJobRequest]) (*connect.Response[v1.ReplayJobResponse], error)
	// Lease streams job assignments to a worker as they become available for the
	// requested queue, up to max_in_flight concurrently-leased jobs at a time.
	Lease(context.Context, *connect.Request[v1.LeaseRequest], *connect.ServerStream[v1.LeaseResponse]) error
	// Ack marks a leased job as successfully completed.
	Ack(context.Context, *connect.Request[v1.AckRequest]) (*connect.Response[v1.AckResponse], error)
	// Nack marks a leased job as failed. The broker schedules it for retry with
	// exponential backoff and jitter, or dead-letters it once max_retries is
	// exhausted.
	Nack(context.Context, *connect.Request[v1.NackRequest]) (*connect.Response[v1.NackResponse], error)
	// Heartbeat renews a job's lease so a long-running handler isn't reclaimed as
	// if it had crashed.
	Heartbeat(context.Context, *connect.Request[v1.HeartbeatRequest]) (*connect.Response[v1.HeartbeatResponse], error)
}

// NewBrokerServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewBrokerServiceHandler(svc BrokerServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	brokerServiceMethods := v1.File_conveyor_v1_queue_proto.Services().ByName("BrokerService").Methods()
	brokerServiceSubmitHandler := connect.NewUnaryHandler(
		BrokerServiceSubmitProcedure,
		svc.Submit,
		connect.WithSchema(brokerServiceMethods.ByName("Submit")),
		connect.WithHandlerOptions(opts...),
	)
	brokerServiceGetHandler := connect.NewUnaryHandler(
		BrokerServiceGetProcedure,
		svc.Get,
		connect.WithSchema(brokerServiceMethods.ByName("Get")),
		connect.WithHandlerOptions(opts...),
	)
	brokerServiceStatsHandler := connect.NewUnaryHandler(
		BrokerServiceStatsProcedure,
		svc.Stats,
		connect.WithSchema(brokerServiceMethods.ByName("Stats")),
		connect.WithHandlerOptions(opts...),
	)
	brokerServiceListJobsHandler := connect.NewUnaryHandler(
		BrokerServiceListJobsProcedure,
		svc.ListJobs,
		connect.WithSchema(brokerServiceMethods.ByName("ListJobs")),
		connect.WithHandlerOptions(opts...),
	)
	brokerServiceReplayJobHandler := connect.NewUnaryHandler(
		BrokerServiceReplayJobProcedure,
		svc.ReplayJob,
		connect.WithSchema(brokerServiceMethods.ByName("ReplayJob")),
		connect.WithHandlerOptions(opts...),
	)
	brokerServiceLeaseHandler := connect.NewServerStreamHandler(
		BrokerServiceLeaseProcedure,
		svc.Lease,
		connect.WithSchema(brokerServiceMethods.ByName("Lease")),
		connect.WithHandlerOptions(opts...),
	)
	brokerServiceAckHandler := connect.NewUnaryHandler(
		BrokerServiceAckProcedure,
		svc.Ack,
		connect.WithSchema(brokerServiceMethods.ByName("Ack")),
		connect.WithHandlerOptions(opts...),
	)
	brokerServiceNackHandler := connect.NewUnaryHandler(
		BrokerServiceNackProcedure,
		svc.Nack,
		connect.WithSchema(brokerServiceMethods.ByName("Nack")),
		connect.WithHandlerOptions(opts...),
	)
	brokerServiceHeartbeatHandler := connect.NewUnaryHandler(
		BrokerServiceHeartbeatProcedure,
		svc.Heartbeat,
		connect.WithSchema(brokerServiceMethods.ByName("Heartbeat")),
		connect.WithHandlerOptions(opts...),
	)
	return "/conveyor.v1.BrokerService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case BrokerServiceSubmitProcedure:
			brokerServiceSubmitHandler.ServeHTTP(w, r)
		case BrokerServiceGetProcedure:
			brokerServiceGetHandler.ServeHTTP(w, r)
		case BrokerServiceStatsProcedure:
			brokerServiceStatsHandler.ServeHTTP(w, r)
		case BrokerServiceListJobsProcedure:
			brokerServiceListJobsHandler.ServeHTTP(w, r)
		case BrokerServiceReplayJobProcedure:
			brokerServiceReplayJobHandler.ServeHTTP(w, r)
		case BrokerServiceLeaseProcedure:
			brokerServiceLeaseHandler.ServeHTTP(w, r)
		case BrokerServiceAckProcedure:
			brokerServiceAckHandler.ServeHTTP(w, r)
		case BrokerServiceNackProcedure:
			brokerServiceNackHandler.ServeHTTP(w, r)
		case BrokerServiceHeartbeatProcedure:
			brokerServiceHeartbeatHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedBrokerServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedBrokerServiceHandler struct{}

func (UnimplementedBrokerServiceHandler) Submit(context.Context, *connect.Request[v1.SubmitRequest]) (*connect.Response[v1.SubmitResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("conveyor.v1.BrokerService.Submit is not implemented"))
}

func (UnimplementedBrokerServiceHandler) Get(context.Context, *connect.Request[v1.GetRequest]) (*connect.Response[v1.GetResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("conveyor.v1.BrokerService.Get is not implemented"))
}

func (UnimplementedBrokerServiceHandler) Stats(context.Context, *connect.Request[v1.StatsRequest]) (*connect.Response[v1.StatsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("conveyor.v1.BrokerService.Stats is not implemented"))
}

func (UnimplementedBrokerServiceHandler) ListJobs(context.Context, *connect.Request[v1.ListJobsRequest]) (*connect.Response[v1.ListJobsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("conveyor.v1.BrokerService.ListJobs is not implemented"))
}

func (UnimplementedBrokerServiceHandler) ReplayJob(context.Context, *connect.Request[v1.ReplayJobRequest]) (*connect.Response[v1.ReplayJobResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("conveyor.v1.BrokerService.ReplayJob is not implemented"))
}

func (UnimplementedBrokerServiceHandler) Lease(context.Context, *connect.Request[v1.LeaseRequest], *connect.ServerStream[v1.LeaseResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("conveyor.v1.BrokerService.Lease is not implemented"))
}

func (UnimplementedBrokerServiceHandler) Ack(context.Context, *connect.Request[v1.AckRequest]) (*connect.Response[v1.AckResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("conveyor.v1.BrokerService.Ack is not implemented"))
}

func (UnimplementedBrokerServiceHandler) Nack(context.Context, *connect.Request[v1.NackRequest]) (*connect.Response[v1.NackResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("conveyor.v1.BrokerService.Nack is not implemented"))
}

func (UnimplementedBrokerServiceHandler) Heartbeat(context.Context, *connect.Request[v1.HeartbeatRequest]) (*connect.Response[v1.HeartbeatResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("conveyor.v1.BrokerService.Heartbeat is not implemented"))
}
