// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: conveyor/v1/queue.proto

package conveyorv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	v1 "conveyor/internal/genproto/conveyor/v1"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// BrokerName is the fully-qualified name of the Broker service.
	BrokerName = "conveyor.v1.Broker"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// BrokerLeaseProcedure is the fully-qualified name of the Broker's Lease RPC.
	BrokerLeaseProcedure = "/conveyor.v1.Broker/Lease"
	// BrokerAckProcedure is the fully-qualified name of the Broker's Ack RPC.
	BrokerAckProcedure = "/conveyor.v1.Broker/Ack"
	// BrokerNackProcedure is the fully-qualified name of the Broker's Nack RPC.
	BrokerNackProcedure = "/conveyor.v1.Broker/Nack"
	// BrokerHeartbeatProcedure is the fully-qualified name of the Broker's Heartbeat RPC.
	BrokerHeartbeatProcedure = "/conveyor.v1.Broker/Heartbeat"
)

// BrokerClient is a client for the conveyor.v1.Broker service.
type BrokerClient interface {
	// Lease streams job assignments to a worker as they become available for the
	// requested queue, up to max_in_flight concurrently-leased jobs at a time.
	Lease(context.Context, *connect.Request[v1.LeaseRequest]) (*connect.ServerStreamForClient[v1.LeaseResponse], error)
	// Ack marks a leased job as successfully completed.
	Ack(context.Context, *connect.Request[v1.AckRequest]) (*connect.Response[v1.AckResponse], error)
	// Nack marks a leased job as failed. The broker schedules it for retry with
	// exponential backoff and jitter, or dead-letters it if max_retries is exhausted.
	Nack(context.Context, *connect.Request[v1.NackRequest]) (*connect.Response[v1.NackResponse], error)
	// Heartbeat renews a job's lease so a long-running handler isn't reclaimed as if
	// it had crashed.
	Heartbeat(context.Context, *connect.Request[v1.HeartbeatRequest]) (*connect.Response[v1.HeartbeatResponse], error)
}

// NewBrokerClient constructs a client for the conveyor.v1.Broker service. By default, it uses the
// Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewBrokerClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) BrokerClient {
	baseURL = strings.TrimRight(baseURL, "/")
	brokerMethods := v1.File_conveyor_v1_queue_proto.Services().ByName("Broker").Methods()
	return &brokerClient{
		lease: connect.NewClient[v1.LeaseRequest, v1.LeaseResponse](
			httpClient,
			baseURL+BrokerLeaseProcedure,
			connect.WithSchema(brokerMethods.ByName("Lease")),
			connect.WithClientOptions(opts...),
		),
		ack: connect.NewClient[v1.AckRequest, v1.AckResponse](
			httpClient,
			baseURL+BrokerAckProcedure,
			connect.WithSchema(brokerMethods.ByName("Ack")),
			connect.WithClientOptions(opts...),
		),
		nack: connect.NewClient[v1.NackRequest, v1.NackResponse](
			httpClient,
			baseURL+BrokerNackProcedure,
			connect.WithSchema(brokerMethods.ByName("Nack")),
			connect.WithClientOptions(opts...),
		),
		heartbeat: connect.NewClient[v1.HeartbeatRequest, v1.HeartbeatResponse](
			httpClient,
			baseURL+BrokerHeartbeatProcedure,
			connect.WithSchema(brokerMethods.ByName("Heartbeat")),
			connect.WithClientOptions(opts...),
		),
	}
}

// brokerClient implements BrokerClient.
type brokerClient struct {
	lease     *connect.Client[v1.LeaseRequest, v1.LeaseResponse]
	ack       *connect.Client[v1.AckRequest, v1.AckResponse]
	nack      *connect.Client[v1.NackRequest, v1.NackResponse]
	heartbeat *connect.Client[v1.HeartbeatRequest, v1.HeartbeatResponse]
}

// Lease calls conveyor.v1.Broker.Lease.
func (c *brokerClient) Lease(ctx context.Context, req *connect.Request[v1.LeaseRequest]) (*connect.ServerStreamForClient[v1.LeaseResponse], error) {
	return c.lease.CallServerStream(ctx, req)
}

// Ack calls conveyor.v1.Broker.Ack.
func (c *brokerClient) Ack(ctx context.Context, req *connect.Request[v1.AckRequest]) (*connect.Response[v1.AckResponse], error) {
	return c.ack.CallUnary(ctx, req)
}

// Nack calls conveyor.v1.Broker.Nack.
func (c *brokerClient) Nack(ctx context.Context, req *connect.Request[v1.NackRequest]) (*connect.Response[v1.NackResponse], error) {
	return c.nack.CallUnary(ctx, req)
}

// Heartbeat calls conveyor.v1.Broker.Heartbeat.
func (c *brokerClient) Heartbeat(ctx context.Context, req *connect.Request[v1.HeartbeatRequest]) (*connect.Response[v1.HeartbeatResponse], error) {
	return c.heartbeat.CallUnary(ctx, req)
}

// BrokerHandler is an implementation of the conveyor.v1.Broker service.
type BrokerHandler interface {
	// Lease streams job assignments to a worker as they become available for the
	// requested queue, up to max_in_flight concurrently-leased jobs at a time.
	Lease(context.Context, *connect.Request[v1.LeaseRequest], *connect.ServerStream[v1.LeaseResponse]) error
	// Ack marks a leased job as successfully completed.
	Ack(context.Context, *connect.Request[v1.AckRequest]) (*connect.Response[v1.AckResponse], error)
	// Nack marks a leased job as failed. The broker schedules it for retry with
	// exponential backoff and jitter, or dead-letters it if max_retries is exhausted.
	Nack(context.Context, *connect.Request[v1.NackRequest]) (*connect.Response[v1.NackResponse], error)
	// Heartbeat renews a job's lease so a long-running handler isn't reclaimed as if
	// it had crashed.
	Heartbeat(context.Context, *connect.Request[v1.HeartbeatRequest]) (*connect.Response[v1.HeartbeatResponse], error)
}

// NewBrokerHandler builds an HTTP handler from the service implementation. It returns the path on
// which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewBrokerHandler(svc BrokerHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	brokerMethods := v1.File_conveyor_v1_queue_proto.Services().ByName("Broker").Methods()
	brokerLeaseHandler := connect.NewServerStreamHandler(
		BrokerLeaseProcedure,
		svc.Lease,
		connect.WithSchema(brokerMethods.ByName("Lease")),
		connect.WithHandlerOptions(opts...),
	)
	brokerAckHandler := connect.NewUnaryHandler(
		BrokerAckProcedure,
		svc.Ack,
		connect.WithSchema(brokerMethods.ByName("Ack")),
		connect.WithHandlerOptions(opts...),
	)
	brokerNackHandler := connect.NewUnaryHandler(
		BrokerNackProcedure,
		svc.Nack,
		connect.WithSchema(brokerMethods.ByName("Nack")),
		connect.WithHandlerOptions(opts...),
	)
	brokerHeartbeatHandler := connect.NewUnaryHandler(
		BrokerHeartbeatProcedure,
		svc.Heartbeat,
		connect.WithSchema(brokerMethods.ByName("Heartbeat")),
		connect.WithHandlerOptions(opts...),
	)
	return "/conveyor.v1.Broker/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case BrokerLeaseProcedure:
			brokerLeaseHandler.ServeHTTP(w, r)
		case BrokerAckProcedure:
			brokerAckHandler.ServeHTTP(w, r)
		case BrokerNackProcedure:
			brokerNackHandler.ServeHTTP(w, r)
		case BrokerHeartbeatProcedure:
			brokerHeartbeatHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedBrokerHandler returns CodeUnimplemented from all methods.
type UnimplementedBrokerHandler struct{}

func (UnimplementedBrokerHandler) Lease(context.Context, *connect.Request[v1.LeaseRequest], *connect.ServerStream[v1.LeaseResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("conveyor.v1.Broker.Lease is not implemented"))
}

func (UnimplementedBrokerHandler) Ack(context.Context, *connect.Request[v1.AckRequest]) (*connect.Response[v1.AckResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("conveyor.v1.Broker.Ack is not implemented"))
}

func (UnimplementedBrokerHandler) Nack(context.Context, *connect.Request[v1.NackRequest]) (*connect.Response[v1.NackResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("conveyor.v1.Broker.Nack is not implemented"))
}

func (UnimplementedBrokerHandler) Heartbeat(context.Context, *connect.Request[v1.HeartbeatRequest]) (*connect.Response[v1.HeartbeatResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("conveyor.v1.Broker.Heartbeat is not implemented"))
}
